### ISSUE TITLE
Pudú se cae con el script de los temblores

### ISSUE THREAD

**Issue by hectorpalmatellez** [hashtagchile/pudu-bot#100]
![crash](http://i.xewa.cl/Yh1kubd5jJ.png)

Probé lo que devuelve y funciona, pero después se muere y no vuelve a levantarse, por lo que tuve que hacer rollback. ¿Se pueden limitar los resultados? Yo creo que 3 está bien.

**Comment by juanbrujo** [comment]
limitare los resultados a temblores mayores a grado 6

**Comment by hectorpalmatellez** [comment]
![miedito](http://www.mouthymag.com/wp-content/uploads/2014/03/Reporter-Earthquake-scared-gif.gif)

Está bien.

**Comment by hectorpalmatellez** [comment]
Este parece que murió con el #101
