### ISSUE TITLE
Tilde en timezone.coffee

### ISSUE THREAD

**Issue by hectorpalmatellez** [hashtagchile/pudu-bot#33]
Debería aceptar `qué hora` (con tilde), aquí:

https://github.com/hashtagchile/pudu-bot/blob/master/scripts/timezone.coffee#L18

**Comment by tmayr** [comment]
Y si sacamos TODAS LAS TILDES?

**Comment by hectorpalmatellez** [comment]
Tendríamos que conversarlo con @daniellr. Es una decisión demasiado importante.

![Pooh](http://media.giphy.com/media/777Aby0ZetYE8/giphy.gif)

**Comment by juanbrujo** [comment]
voy a arreglar esto altiro no lo habia visto

**Comment by juanbrujo** [comment]
listo https://github.com/hashtagchile/pudu-bot/pull/55
