### ISSUE TITLE
Readme para contribuir con Pudú

### ISSUE THREAD

**Issue by hectorpalmatellez** [hashtagchile/pudu-bot#79]
![pudú patita](http://i2.cdn.turner.com/cnnnext/dam/assets/150609105118-baby-zoo-animals---pudu-fawn-exlarge-169.jpg)

Debemos crear un minitutorial explicando cómo aportar al Pudú. Podría tener, entre otras cosas:

* Qué tecnologías soporta
* Buenas prácticas
* Ejemplos de acciones
* ...

**Comment by hectorpalmatellez** [comment]
Esto lo terminó @juanbrujo :clap: :pudu: :jorge:

**Comment by juanbrujo** [comment]
fue un aporte creo q puede ser mejor IMHO
